export const projectName = "deepseek-workbench";
export const releaseScope = "v0.1.0";
export const currentTaskId = "DW-P0A-004";
export const nextTaskId = "DW-P0A-005";

export type RuntimeSkeletonStatus = {
  projectName: typeof projectName;
  releaseScope: typeof releaseScope;
  currentTaskId: typeof currentTaskId;
  nextTaskId: typeof nextTaskId;
  implementedCapabilities: string[];
  disabledUntilLaterTasks: string[];
};

export function getRuntimeSkeletonStatus(): RuntimeSkeletonStatus {
  return {
    projectName,
    releaseScope,
    currentTaskId,
    nextTaskId,
    implementedCapabilities: [
      "workspace skeleton",
      "runtime package",
      "event store",
      "replay demo",
      "DeepSeek client adapter",
      "fake DeepSeek client",
      "ConversationEngine invariants"
    ],
    disabledUntilLaterTasks: [
      "ConversationEngine",
      "browser extension permissions",
      "desktop control"
    ]
  };
}

export * from "./conversation/index.js";
export * from "./agents/index.js";
export * from "./bridge/index.js";
export * from "./capabilities/index.js";
export * from "./control-plane/index.js";
export * from "./context/index.js";
export * from "./memory/index.js";
export * from "./deepseek/index.js";
export * from "./events/index.js";
export * from "./execution/index.js";
export * from "./flows/index.js";
export * as modelPlane from "./models/index.js";
export {
  getDeepSeekCapabilityProfile,
  listDeepSeekCapabilityProfiles,
  runLiveDeepSeekProposalAdapter,
  runLiveProposalEvaluation,
  runLiveProposalEvaluationCase,
  runLiveProposalOfflineEvaluation,
  runLiveProposalOfflineEvaluationCase,
  normalizeLiveProposalGoldenCase,
  parseLiveProposalGoldenCase,
  buildLiveProposalEvaluationTelemetryAudit,
  buildLiveProposalTelemetryRedactionAudit,
  buildLiveProposalValidationIntegration,
  buildLiveProposalFailureMetrics,
  buildLiveProposalApiKeyPolicy,
  buildLiveProposalRequest,
  buildPatchProposalDryRequest,
  createFakePatchProposalModel,
  normalizeLegacyDeepSeekModelId,
  normalizeModelPatchProposalDraft,
  parseModelPatchProposalDraft,
  repairModelPatchProposalDraft,
  runPatchProposalDryAdapter,
  runPatchProposalHarness,
  runPatchProposalHarnessCase,
  summarizeLiveDeepSeekProposalAdapterResult,
  summarizeLiveProposalEvaluationReport,
  summarizeLiveProposalEvaluationTelemetryAudit,
  summarizeLiveProposalFailureMetrics,
  summarizeLiveProposalGoldenCase,
  summarizeLiveProposalOfflineEvaluationReport,
  summarizeLiveProposalTelemetryRedactionAudit,
  summarizeLiveProposalValidationIntegration,
  summarizePatchProposalDryAdapterResult,
  summarizeLiveProposalApiKeyPolicy,
  summarizeLiveProposalRequestBuild,
  summarizePatchProposalHarnessReport,
  summarizeModelPatchProposalDraft,
  summarizePatchProposalRepairResult,
  validatePatchProposalDryAdapterInput,
  validateLiveDeepSeekProposalAdapterInput,
  validateLiveProposalEvaluationInput,
  validateLiveProposalEvaluationTelemetryAuditInput,
  validateLiveProposalFailureMetricsInput,
  validateLiveProposalOfflineEvaluationInput,
  validateLiveProposalGoldenCase,
  validateLiveProposalTelemetryRedactionAuditInput,
  validateLiveProposalValidationIntegrationInput,
  validateLiveProposalApiKeyPolicyInput,
  validateLiveProposalRequestBuilderInput,
  validateModelPatchProposalDraft,
  validatePatchProposalRepairInput,
  runDeepSeekCapabilityDryProbe
} from "./models/index.js";
export type {
  DeepSeekCapabilityInvariant,
  DeepSeekCapabilityProfile,
  DeepSeekCapabilityProbeInput,
  DeepSeekCapabilityProbeResult,
  DeepSeekCapabilityProbeStatus,
  DeepSeekCapabilityWarning,
  DeepSeekCapabilityWarningKind,
  DeepSeekFeatureSupport,
  DeepSeekLegacyAlias,
  DeepSeekModelFamily,
  DeepSeekModelId as DeepSeekCapabilityModelId,
  FakePatchProposalModel,
  FakePatchProposalModelResponse,
  LiveDeepSeekApiKeyResolution,
  LiveDeepSeekApiKeyResolver,
  LiveDeepSeekProposalAdapterFinding,
  LiveDeepSeekProposalAdapterFindingKind,
  LiveDeepSeekProposalAdapterInput,
  LiveDeepSeekProposalAdapterReadiness,
  LiveDeepSeekProposalAdapterResult,
  LiveDeepSeekProposalAdapterSeverity,
  LiveDeepSeekProposalAdapterStatus,
  LiveDeepSeekProposalProposalSummary,
  LiveDeepSeekProposalRepairSummary,
  LiveDeepSeekProposalTransport,
  LiveDeepSeekProposalTransportRequest,
  LiveDeepSeekProposalTransportResponse,
  LiveDeepSeekProposalUsageSummary,
  LiveDeepSeekProposalValidationSummary,
  LiveProposalEvaluationCaseInput,
  LiveProposalEvaluationCaseResult,
  LiveProposalEvaluationCaseStatus,
  LiveProposalEvaluationFailureTaxonomySummary,
  LiveProposalEvaluationFinding,
  LiveProposalEvaluationFindingKind,
  LiveProposalEvaluationInput,
  LiveProposalEvaluationMetric,
  LiveProposalEvaluationMode,
  LiveProposalEvaluationReadiness,
  LiveProposalEvaluationReport,
  LiveProposalEvaluationSeverity,
  LiveProposalEvaluationStatus,
  LiveProposalEvaluationTelemetryAuditSummary,
  LiveProposalEvaluationTelemetryAuditInput,
  LiveProposalEvaluationTelemetryAuditReport,
  LiveProposalEvaluationTelemetryAuditStatus,
  LiveProposalEvaluationTelemetryFinding,
  LiveProposalEvaluationTelemetryFindingKind,
  LiveProposalEvaluationTelemetryRecord,
  LiveProposalEvaluationTelemetryRecordKind,
  LiveProposalEvaluationTelemetryReadiness,
  LiveProposalEvaluationTelemetrySeverity,
  LiveProposalEvaluationUsageTelemetrySummary,
  LiveProposalEvaluationUsageSummary,
  LiveProposalEvaluationRedactionSummary,
  LiveProposalExpectationMetrics,
  LiveProposalFailureMetricsFinding,
  LiveProposalFailureMetricsFindingKind,
  LiveProposalFailureMetricsInput,
  LiveProposalFailureMetricsReadiness,
  LiveProposalFailureMetricsReport,
  LiveProposalFailureMetricsSeverity,
  LiveProposalFailureMetricsStatus,
  LiveProposalFailureTaxonomyMetrics,
  LiveProposalGoldenCase,
  LiveProposalGoldenCaseContextRef,
  LiveProposalGoldenCaseDifficulty,
  LiveProposalGoldenCaseEvidenceRef,
  LiveProposalGoldenCaseExpectedFailure,
  LiveProposalGoldenCaseExpectedMetric,
  LiveProposalGoldenCaseExpectedOutcome,
  LiveProposalGoldenCaseFailureCategory,
  LiveProposalGoldenCaseFinding,
  LiveProposalGoldenCaseFindingKind,
  LiveProposalGoldenCaseInput,
  LiveProposalGoldenCaseMode,
  LiveProposalGoldenCaseOptions,
  LiveProposalGoldenCaseReadiness,
  LiveProposalGoldenCaseSeverity,
  LiveProposalGoldenCaseValidationResult,
  LiveProposalGoldenCaseValidationStatus,
  LiveProposalGoldenCaseWorkspaceRef,
  LiveProposalFailureTaxonomySummary,
  LiveProposalRepairMetrics,
  LiveProposalSchemaMetrics,
  LiveProposalOfflineEvaluationCaseInput,
  LiveProposalOfflineEvaluationCaseResult,
  LiveProposalOfflineEvaluationCaseStatus,
  LiveProposalOfflineEvaluationFinding,
  LiveProposalOfflineEvaluationFindingKind,
  LiveProposalOfflineEvaluationInput,
  LiveProposalOfflineEvaluationMetric,
  LiveProposalOfflineEvaluationMode,
  LiveProposalOfflineEvaluationReadiness,
  LiveProposalOfflineEvaluationReport,
  LiveProposalOfflineEvaluationSeverity,
  LiveProposalOfflineEvaluationStatus,
  LiveProposalOfflineEvaluationUsageSummary,
  LiveProposalUsageMetrics,
  LiveProposalTelemetryMode,
  LiveProposalTelemetryReadiness,
  LiveProposalTelemetryRecord,
  LiveProposalTelemetryRecordKind,
  LiveProposalTelemetryRedactionAudit,
  LiveProposalTelemetryRedactionAuditInput,
  LiveProposalTelemetryRedactionAuditStatus,
  LiveProposalTelemetryRedactionFinding,
  LiveProposalTelemetryRedactionFindingKind,
  LiveProposalTelemetryRedactionSeverity,
  LiveProposalTelemetryUsageSummary,
  LiveProposalRedactionSummary,
  LiveProposalValidationGate,
  LiveProposalValidationGateKind,
  LiveProposalValidationIntegration,
  LiveProposalValidationIntegrationFinding,
  LiveProposalValidationIntegrationFindingKind,
  LiveProposalValidationIntegrationInput,
  LiveProposalValidationIntegrationReadiness,
  LiveProposalValidationIntegrationSeverity,
  LiveProposalValidationIntegrationStatus,
  LiveProposalApiKeyPolicy,
  LiveProposalApiKeyPolicyFinding,
  LiveProposalApiKeyPolicyFindingKind,
  LiveProposalApiKeyPolicyInput,
  LiveProposalApiKeyPolicyReadiness,
  LiveProposalApiKeyPolicySeverity,
  LiveProposalApiKeyPolicyStatus,
  LiveProposalApiKeySource,
  LiveProposalApiKeySourceType,
  LiveProposalOptInGate,
  LiveProposalOptInScope,
  LiveProposalPromptBoundary,
  LiveProposalPromptMode,
  LiveProposalRequestBoundary,
  LiveProposalRequestBuildResult,
  LiveProposalRequestBuildStatus,
  LiveProposalRequestBuilderInput,
  LiveProposalRequestEnvelope,
  LiveProposalRequestFinding,
  LiveProposalRequestFindingKind,
  LiveProposalRequestReadiness,
  LiveProposalRequestSafetyInstructions,
  LiveProposalRequestSeverity,
  LiveProposalThinkingMode,
  ModelPatchProposal,
  ModelPatchProposalEvidenceRef,
  ModelPatchProposalFinding,
  ModelPatchProposalFindingKind,
  ModelPatchProposalInput,
  ModelPatchProposalOperation,
  ModelPatchProposalPathSummary,
  ModelPatchProposalReadiness,
  ModelPatchProposalRiskNote,
  ModelPatchProposalSeverity,
  ModelPatchProposalValidationResult,
  PatchProposalDryAdapterFinding,
  PatchProposalDryAdapterFindingKind,
  PatchProposalDryAdapterInput,
  PatchProposalDryAdapterReadiness,
  PatchProposalDryAdapterResult,
  PatchProposalDryAdapterSeverity,
  PatchProposalDryAdapterStatus,
  PatchProposalDryModelClient,
  PatchProposalDryModelRequest,
  PatchProposalDryModelResponse,
  PatchProposalDryProposalSummary,
  PatchProposalDryProposalValidation,
  PatchProposalDryUsageSummary,
  PatchProposalHarnessCase,
  PatchProposalHarnessCaseStatus,
  PatchProposalHarnessFinding,
  PatchProposalHarnessFindingKind,
  PatchProposalHarnessInput,
  PatchProposalHarnessReadiness,
  PatchProposalHarnessReport,
  PatchProposalHarnessResult,
  PatchProposalHarnessSeverity,
  PatchProposalHarnessStatus,
  PatchProposalHarnessValidationSummary,
  PatchProposalRepairAttempt,
  PatchProposalRepairFinding,
  PatchProposalRepairFindingKind,
  PatchProposalRepairInput,
  PatchProposalRepairOperation,
  PatchProposalRepairOperationKind,
  PatchProposalRepairProposalSummary,
  PatchProposalRepairProposalValidation,
  PatchProposalRepairReadiness,
  PatchProposalRepairResult,
  PatchProposalRepairSeverity,
  PatchProposalRepairSourceKind,
  PatchProposalRepairStatus
} from "./models/index.js";
export * from "./web/index.js";
export * from "./workspace-index/index.js";
export {
  ToolBroker,
  createToolCallRequestFromDeepSeekToolCall
} from "./tools/tool-broker.js";
export { ToolBrokerError } from "./tools/errors.js";
export { decideToolPermission } from "./tools/permission-policy.js";
export { compareToolRisk, isRiskAtMost } from "./tools/risk.js";
export { ToolRegistry } from "./tools/tool-registry.js";
export type {
  ToolArgumentSummary,
  ToolBrokerErrorKind,
  ToolBrokerOptions,
  ToolCallRequest,
  ToolCallResult,
  ToolCallSource,
  ToolDefinitionRuntime,
  ToolExecutionStatus,
  ToolName,
  ToolPermissionDecision,
  ToolPermissionPolicy,
  ToolRiskLevel
} from "./tools/types.js";
export * from "./workspace/index.js";
